feat: added 2 scenarios related to #161
Hypertopic/HyperGlosae pull request #162
Opened 2024-03-27 16:38 UTC by raphaelweis

This adds the cases mentioned in #161 to the feature.

2024-04-02 11:41 UTC, benel requested changes
Thank you very much for your interesting contribution @raphaelweis, @Barnabepetit, @louisduhalberruer, @nitram35, @petitfa1. 

1. Please follow the instructions given on Moodle:
> Dans une branche thématique (nommée selon le ticket traité, ex : "fix-999"), préparez une "contribution" (commit)  avec vos scénarios modifiés. 
> Veillez à ce que :
> - le titre soit formaté de la même manière que [les contributions analogues](https://github.com/search?q=repo%3AHypertopic%2FHyperGlosae+%5ESCENARIO+should+see&type=commits&s=committer-date&o=asc) (`SCENARIO: <nom du ticket en anglais> (see #999).`),
> - les co-auteurs apparaissent selon [la syntaxe de GitHub](https://docs.github.com/fr/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).

2. In the discussion, please mention authors' full names  (and check with one another that you agree) on the authorization concerning all the content you will produce in this branch. 

3. Here are also several change requests.

2024-04-02 16:48 UTC, benel requested changes
Thank you very much for your interesting contribution @raphaelweis, @Barnabepetit, @louisduhalberruer, @nitram35, @petitfa1. 

1. Please follow the instructions given on Moodle:
> Dans une branche thématique (nommée selon le ticket traité, ex : "fix-999"), préparez une "contribution" (commit)  avec vos scénarios modifiés. 
> Veillez à ce que :
> - le titre soit formaté de la même manière que [les contributions analogues](https://github.com/search?q=repo%3AHypertopic%2FHyperGlosae+%5ESCENARIO+should+see&type=commits&s=committer-date&o=asc) (`SCENARIO: <nom du ticket en anglais> (see #999).`),
> - les co-auteurs apparaissent selon [la syntaxe de GitHub](https://docs.github.com/fr/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).

2. In the discussion, please mention authors' full names  (and check with one another that you agree) on the authorization concerning all the content you will produce in this branch. 

3. Here are also several change requests. 

4. The Pull request should be in draft mode until a commit fix is pushed in the branch.

2024-04-02 16:48 UTC, benel commented on features/edit_glose_content.feature
> +      Acteur
without `s`?!

2024-04-02 16:48 UTC, benel commented on features/edit_glose_content.feature
> +      Acteur
without `s`?!

2024-04-02 16:48 UTC, benel commented on features/edit_glose_content.feature
> +  Alors le bloc affiche
A clause with the user as the subject of the verb would be preferred.

2024-04-02 16:48 UTC, benel commented on features/edit_glose_content.feature
> +  Alors le bloc affiche
A clause with the user as the subject of the verb would be preferred.

2024-04-02 19:06 UTC, raphaelweis commented
We have amended the previous commit to satisfy the review.

2024-04-10 11:53 UTC, benel commented
Thank you for your updates @raphaelweis, @Barnabepetit, @louisduhalberruer, @nitram35, @petitfa1.

- The content is great.
- The history is fine, except a little problem in the second commit: `SCENARIO` should be followed by the title of a feature or a fix being scenarized. I suggest you to rephrase the whole commit title it in something like `PROCESS: Scenario steps related to glose blocks should be reusable.`. See that as a nice opportunity for your entire team to test "interactive rebase". Of course I can help you if needed.

2024-04-26 14:56 UTC, benel commented
Thank you for your contribution @raphaelweis, @Barnabepetit, @louisduhalberruer, @nitram35, @petitfa1.

Is it your last version?

I thought it was done but it seems that, without your fix, your test that should pass fails. Is this right?

2024-04-26 15:12 UTC, raphaelweis commented
> Thank you for your contribution @raphaelweis, @Barnabepetit, @louisduhalberruer, @nitram35, @petitfa1.
> 
> Is it your last version?
> 
> I thought it was done but it seems that, without your fix, your test that should pass fails. Is this right?

I believe the implementation of the fix to be correct, but it broke multiple CSS selectors in the test implementations. I have looked at it a bit but so far no luck fixing the failing tests. I'll have another look at it this weekend or next week.

Once we get all the tests to pass again it should be good to merge.

2024-04-27 20:54 UTC, merged

2024-04-27 21:06 UTC, benel commented
Thank you for your answer @raphaelweis.
I've found what was the problem with the tests.

On blank gloses, the testing bot – which is far faster than a normal user – "clicks" on your new block place holder before it is replaced by "&lt;TEXT&gt;".

The tests were fixed with 40c68972f27f127fcd5db4c7ca7ddd03efbad777.

Your branch is now merged. Well done  @raphaelweis, @Barnabepetit, @louisduhalberruer, @nitram35, @petitfa1!