SAMPLE : part of a church stained glass' visit
Hypertopic/HyperGlosae pull request #54
Opened 2023-03-28 14:32 UTC by vallhallalm

We, [Sébastien Bacoup, Amal Chikhaou, Matéo Condat, Léo Kemplaire, Louis Magnier, Le Vu Long Tran], hereby grant to Hyperglosae maintainers the right to publish our contribution under the terms of any licenses the Free Software Foundation classifies as Free Software Licenses.

2023-03-30 08:23 UTC, benel requested changes
Thank you very much for this contribution.

The use case is really interesting.

However by referring directly the picture in your own document, there is an ambiguity in who is  the author of what (i.e. you are not the author of the picture), which means that: 
- you don't use the main feature of the software,
- there is no more links between different visits that would include the same picture.

If your team need a work session with me to think about the possible network, I can help you.

2023-03-30 08:23 UTC, benel commented on samples/eglise-st-jean.json
> +    "dc_license": "https://creativecommons.org/licenses/by-sa/4.0/"
The license is unknown. You should let it undefined (which means "All rights reserved").

2023-03-30 08:23 UTC, benel commented on samples/vitrail-1-1.json
> +  "dc_creator": "Louis Magnier",
There is an ambiguity in this document about who is the author of what...

2023-03-30 08:23 UTC, benel commented on samples/vitrail-2.json
> +  "dc_creator": "Louis Magnier",
Idem.

2023-03-30 08:23 UTC, benel commented on samples/vitrail1.json
> +"dc_creator": "Louis Magnier",
Idem.

2023-04-04 12:41 UTC, vallhallalm commented
Normally I managed to do the changes requested @benel

2023-04-29 15:02 UTC, benel commented
Thank you for your new commits @Hypertopic/histoire-de-l-art. 
However there is some confusion in this pull request (probably because it points to the `main` branch). 
I suggest you to close this pull request and create a new pull request on a new branch with the new samples you worked on last week.

2023-05-02 15:19 UTC, closed without merging